# basic options
title: GraphTree's Blog
author: GraphTree
email: graphnodesed@gmail.com
description: Abotu Applied Math and data
github_username:  GraphTree

# Build settings
markdown: kramdown
theme: minima
